### ISSUE TITLE
Fix NullPointerException in OneToManyBiMap.put()

### ISSUE THREAD

**Issue by hazmatsuitor** [Rsranger65/Blockade-Runner#22]
Caused by LD31.java:188 `input.addAction(CTL_RESTART, () -> {` (etc.)

Stack trace:

Exception in thread "Animation Thread" java.lang.NullPointerException
    at net.kopeph.ld31.util.OneToManyBiMap.put(OneToManyBiMap.java:71)
    at net.kopeph.ld31.Input.addAction(Input.java:92)
    at net.kopeph.ld31.Input.addAction(Input.java:86)
    at net.kopeph.ld31.LD31.setup(LD31.java:188)
    at processing.core.PApplet.handleDraw(PApplet.java:2361)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
    at processing.core.PApplet.run(PApplet.java:2256)
    at java.lang.Thread.run(Unknown Source)

**Comment by win93** [comment]
Can you give me reproduction instructions?

**Comment by hazmatsuitor** [comment]
Build and run from the miles-01 branch.

**Comment by win93** [comment]
right ok, You need to sync your project maybe?

**Comment by win93** [comment]
Reproduction Instructions: Clear out preferences (OS Dependent), and Run (Consistent Fail on load)
